In [1]:
#Create a NumPy ndarray Object

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#Dimensions in Arrays
#A dimension in arrays is one level of array depth (nested arrays).
#0-D array

import numpy as np

arr = np.array(42)
print(arr)

#1-d array

arr = np.array([1,2,3,4,5])
print(arr)


#2-D array	

arr = np.array([[1,2,3],[4,5,6]])
print(arr)


#3-D array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])
print(arr)



42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]


In [6]:
#
#Check Number of Dimensions?
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

import numpy as np

a = np.array(32)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[3,4,5]])
d= np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


In [8]:
#Higher Dimensional Arrays
#An array can have any number of dimensions.

#When the array is created, you can define the number of dimensions by using the ndmin argument.


import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print('number of dimensions:', arr.ndim)

[1 2 3 4 5]
number of dimensions: 1


In [9]:
# accessing array elements

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[2])

3


In [10]:
arr = np.array([1,2,3,4,5])
print(arr[2] + arr[1])

5


In [11]:
 arr = np.array([[1,2,3],[4,5,6]])
print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 2


In [15]:
 arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on the 2nd row:',arr[1,4])

5th element on the 2nd row: 10


In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [17]:
 arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [21]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [22]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [44]:
arr =np.array([1,2,3,4,5])
x= arr.copy()
arr[0]= 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [31]:
#joining arrays using concatenate()

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [34]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [35]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [36]:
arr = np.array([1,2,3,4,5])
newarr=np.where(arr==5)
print(newarr)

(array([4], dtype=int64),)


In [38]:
arr = np.array([1,1,0,1,0])
newarr = arr.astype(bool)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

True
True
False
True


In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
evenNumbers = np.where(arr% 2 == 0,arr,',')
print(evenNumbers)
#index of even numbers

[',' '2' ',' '4' ',' '6' ',' '8' ',' '10']
